# Generated by Django 2.0.4 on 2018-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Ids',
            fields=[
                ('user_index', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
