# Generated by Django 2.0.4 on 2018-04-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20180427_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_number', models.IntegerField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=300)),
                ('song_release', models.CharField(max_length=300)),
                ('song_artist', models.CharField(max_length=200)),
                ('song_year', models.IntegerField()),
            ],
        ),
    ]
